<?php

/*
    Include the autoload.php file as generated by composer
    to load all dependencies.
*/
require __DIR__ . '/../vendor/autoload.php';

error_reporting(E_ALL);

/**
*   Initialize DB.
*/
DB::$user = 'root';
DB::$password = 'password';
DB::$dbName = 'asg';

/**
*   Twig templating functions.
*/
function loadTwig()
{
    // Initialize twig
    Twig_Autoloader::register();
    $loader = new Twig_Loader_Filesystem(__DIR__ . '/templates');
    $twig = new Twig_Environment($loader, array());

    return $twig;
}

function index_handler()
{
    $parse = [];

    // Query all contacts
    $parse['contacts'] = DB::query("SELECT * FROM contacts");

    // Parse query string
    parse_str($_SERVER['QUERY_STRING'], $query);
    $parse['success'] = $query['success'];

    // Render template
    $twig = loadTwig();
    echo $twig->render('contacts_list.html', $parse);
}

function contact_handler($id)
{
    var_dump($_FILES);
    var_dump($_POST);

    // If $_POST, process first.
    if (!empty($_POST)) {
        DB::insertUpdate('contacts', array(
            'id' => $_POST['id'],
            'first_name' => $_POST['first_name'],
            'surname' => $_POST['surname'],
            'cellphone' => $_POST['cellphone'],
            'email' => $_POST['email']
        ));

        header("Location: /?success=1");
    }

    // Parse query string
    parse_str($_SERVER['QUERY_STRING'], $query);

    // Load normal view page.
    $parse = [];
    $twig = loadTwig();

    if (!empty($query['id'])) {
        $parse['contact'] = DB::queryFirstRow("SELECT * FROM contacts WHERE id = %d", $query['id']);
        $parse['submit_button_text'] = 'Update';
    } else {
        $parse['submit_button_text'] = 'Add';
    }

    echo $twig->render('contact_manage.html', $parse);
}

function about_handler()
{
    $twig = loadTwig();
    echo $twig->render('about.html', array('the' => 'variables', 'go' => 'here'));
}

$dispatcher = \FastRoute\simpleDispatcher(function (\FastRoute\RouteCollector $r) {
    // Add routes
    $r->addRoute(['GET', 'POST'], '/', 'index_handler');
    $r->addRoute(['GET', 'POST'], '/manage', 'contact_handler');
    $r->addRoute('GET', '/about', 'about_handler');
});

// Fetch method and URI from somewhere
$httpMethod = $_SERVER['REQUEST_METHOD'];
$uri = $_SERVER['REQUEST_URI'];

// Strip query string (?foo=bar) and decode URI
if (false !== $pos = strpos($uri, '?')) {
    $uri = substr($uri, 0, $pos);
}
$uri = rawurldecode($uri);

$routeInfo = $dispatcher->dispatch($httpMethod, $uri);
switch ($routeInfo[0]) {
    case \FastRoute\Dispatcher::NOT_FOUND:
        // ... 404 Not Found
        break;
    case \FastRoute\Dispatcher::METHOD_NOT_ALLOWED:
        $allowedMethods = $routeInfo[1];
        // ... 405 Method Not Allowed
        break;
    case \FastRoute\Dispatcher::FOUND:
        $handler = $routeInfo[1];
        $vars = $routeInfo[2];
        call_user_func($handler, $vars);
        break;
}

?>
