<?php

/*
    Include the autoload.php file as generated by composer
    to load all dependencies.
*/
require __DIR__ . '/../vendor/autoload.php';

error_reporting(E_ALL);

function loadTwig()
{
    // Initialize twig
    Twig_Autoloader::register();
    $loader = new Twig_Loader_Filesystem(__DIR__ . '/templates');
    $twig = new Twig_Environment($loader, array());

    return $twig;
}

function index_handler()
{
    var_dump($_POST);
    $twig = loadTwig();
    echo $twig->render('contacts_list.html', array('the' => 'variables', 'go' => 'here'));
}

function contact_handler($id)
{
    $twig = loadTwig();
    echo $twig->render('contact_manage.html', array('the' => 'variables', 'go' => 'here'));
}

function about_handler()
{
    $twig = loadTwig();
    echo $twig->render('about.html', array('the' => 'variables', 'go' => 'here'));
}

$dispatcher = \FastRoute\simpleDispatcher(function (\FastRoute\RouteCollector $r) {
    // Add routes
    $r->addRoute(['GET', 'POST'], '/', 'index_handler');
    $r->addRoute('GET', '/manage[/{id}]', 'contact_handler');
    $r->addRoute('GET', '/about', 'about_handler');
});

// Fetch method and URI from somewhere
$httpMethod = $_SERVER['REQUEST_METHOD'];
$uri = $_SERVER['REQUEST_URI'];

// Strip query string (?foo=bar) and decode URI
if (false !== $pos = strpos($uri, '?')) {
    $uri = substr($uri, 0, $pos);
}
$uri = rawurldecode($uri);

$routeInfo = $dispatcher->dispatch($httpMethod, $uri);
switch ($routeInfo[0]) {
    case \FastRoute\Dispatcher::NOT_FOUND:
        // ... 404 Not Found
        break;
    case \FastRoute\Dispatcher::METHOD_NOT_ALLOWED:
        $allowedMethods = $routeInfo[1];
        // ... 405 Method Not Allowed
        break;
    case \FastRoute\Dispatcher::FOUND:
        $handler = $routeInfo[1];
        $vars = $routeInfo[2];
        call_user_func($handler, $vars);
        break;
}

?>
